#define DO_NOTHING 0
#define NEW_GAME 1
#define END_GAME 2
#define PAUSE_GAME 3
#define SHOW_HIDE_HUD 4
#define RESUME_GAME 5

#define FIRST_TOWER_HOVER 6
#define FIRST_TOWER_CLICKED 7
#define SEC_TOWER_HOVER 8
#define SEC_TOWER_CLICKED 9

#define NO_SELECTION 10
#define FIRST_TOWER 11
#define SECOND_TOWER 12

#define SEC_TOWER_MATERIAL 13
#define FIRST_TOWER_MATERIAL 14

#define WINDOW_WIDTH  640
#define WINDOW_HEIGHT 480
